"""Tests for insert_funding_batch() on_conflict deduplication.

Verifies that:
  1. Batch upsert is called with on_conflict="wallet_address,sender_address,hop_level"
  2. The fallback single-row path also uses on_conflict (not bare insert)
  3. Empty input returns 0 without hitting the DB
  4. Inserted count reflects the number of rows in successful batches
  5. id field is stripped from rows before upsert (auto-generated by DB)
"""

from dataclasses import asdict
from unittest.mock import MagicMock, call, patch

import pytest

from src.database.models import WalletFunding
from src.database.supabase_client import SupabaseClient


# ── Helpers ──────────────────────────────────────────────────────────────────

def _make_funding(wallet: str, sender: str, hop: int = 1) -> WalletFunding:
    return WalletFunding(
        wallet_address=wallet,
        sender_address=sender,
        hop_level=hop,
        amount=500.0,
    )


def _make_db() -> SupabaseClient:
    """Return a SupabaseClient with a fully mocked Supabase REST client."""
    db = object.__new__(SupabaseClient)
    db.client = MagicMock()
    return db


# ── Tests ─────────────────────────────────────────────────────────────────────

class TestInsertFundingBatchEmpty:
    def test_empty_list_returns_zero(self):
        db = _make_db()
        result = db.insert_funding_batch([])
        assert result == 0
        db.client.table.assert_not_called()


class TestInsertFundingBatchOnConflict:
    """Batch upsert must pass on_conflict to avoid row duplication."""

    def setup_method(self):
        self.db = _make_db()
        # Chain: table(...).upsert(...).execute() → success
        self.mock_execute = MagicMock(return_value=MagicMock(data=[]))
        self.db.client.table.return_value.upsert.return_value.execute = self.mock_execute

    def test_upsert_called_with_on_conflict(self):
        fundings = [_make_funding("0xAAA", "0xBBB")]
        self.db.insert_funding_batch(fundings)

        upsert_call = self.db.client.table.return_value.upsert
        args, kwargs = upsert_call.call_args
        assert kwargs.get("on_conflict") == "wallet_address,sender_address,hop_level"

    def test_id_stripped_from_rows(self):
        """id must be removed so DB auto-generates it."""
        f = _make_funding("0xAAA", "0xBBB")
        f.id = 999  # simulate existing id
        self.db.insert_funding_batch([f])

        upsert_call = self.db.client.table.return_value.upsert
        rows_sent, _ = upsert_call.call_args
        batch = rows_sent[0]
        assert isinstance(batch, list)
        assert "id" not in batch[0]

    def test_returns_inserted_count(self):
        fundings = [
            _make_funding("0xAAA", "0xBBB"),
            _make_funding("0xAAA", "0xCCC"),
        ]
        result = self.db.insert_funding_batch(fundings)
        assert result == 2

    def test_multiple_batches(self):
        """With batch_size=1, each row is a separate upsert call."""
        fundings = [
            _make_funding("0xAAA", "0xBBB"),
            _make_funding("0xAAA", "0xCCC"),
        ]
        result = self.db.insert_funding_batch(fundings, batch_size=1)
        assert result == 2
        assert self.db.client.table.return_value.upsert.call_count == 2
        # Both calls must include on_conflict
        for c in self.db.client.table.return_value.upsert.call_args_list:
            _, kwargs = c
            assert kwargs.get("on_conflict") == "wallet_address,sender_address,hop_level"


class TestInsertFundingBatchFallback:
    """When batch upsert raises, fallback single-row path must also use on_conflict."""

    def setup_method(self):
        self.db = _make_db()

        # Batch upsert raises; single-row upsert succeeds
        self.db.client.table.return_value.upsert.side_effect = [
            Exception("batch error"),           # first call = batch attempt
            MagicMock(execute=MagicMock()),      # subsequent calls = single-row fallback
        ]

    def test_fallback_uses_upsert_not_insert(self):
        """Fallback must call .upsert() with on_conflict, never bare .insert()."""
        fundings = [_make_funding("0xAAA", "0xBBB")]
        self.db.insert_funding_batch(fundings, batch_size=10)

        # .insert() should never be called
        self.db.client.table.return_value.insert.assert_not_called()

    def test_fallback_passes_on_conflict(self):
        fundings = [_make_funding("0xAAA", "0xBBB")]

        # Reset side_effect: batch fails once, single-row succeeds
        execute_mock = MagicMock()
        self.db.client.table.return_value.upsert.side_effect = None
        call_count = {"n": 0}

        def upsert_side_effect(data, **kwargs):
            call_count["n"] += 1
            if call_count["n"] == 1:
                raise Exception("batch error")
            # Return a chainable mock
            m = MagicMock()
            m.execute.return_value = MagicMock(data=[])
            return m

        self.db.client.table.return_value.upsert.side_effect = upsert_side_effect

        self.db.insert_funding_batch(fundings, batch_size=10)

        # All upsert calls (batch + fallback) must have on_conflict
        for c in self.db.client.table.return_value.upsert.call_args_list:
            _, kwargs = c
            assert kwargs.get("on_conflict") == "wallet_address,sender_address,hop_level"

    def test_fallback_returns_inserted_count(self):
        """Successful fallback rows are counted."""
        fundings = [_make_funding("0xAAA", "0xBBB")]

        call_count = {"n": 0}

        def upsert_side_effect(data, **kwargs):
            call_count["n"] += 1
            if call_count["n"] == 1:
                raise Exception("batch error")
            m = MagicMock()
            m.execute.return_value = MagicMock(data=[])
            return m

        self.db.client.table.return_value.upsert.side_effect = upsert_side_effect

        result = self.db.insert_funding_batch(fundings, batch_size=10)
        assert result == 1

    def test_fallback_skips_failed_rows(self):
        """If single-row upsert also fails, that row is skipped (count not incremented)."""
        fundings = [
            _make_funding("0xAAA", "0xBBB"),
            _make_funding("0xAAA", "0xCCC"),
        ]

        def upsert_side_effect(data, **kwargs):
            raise Exception("always fails")

        self.db.client.table.return_value.upsert.side_effect = upsert_side_effect

        result = self.db.insert_funding_batch(fundings, batch_size=10)
        assert result == 0
